### ISSUE TITLE
Integrated new format with CI build process

### ISSUE THREAD

**Issue by darrencomeau** [VulcanAnalytics/pickles#16]
Pull request now has continuous integration builds executing, make sure that new code and tests are picked up within this process.

[build log](https://ci.appveyor.com/project/dirkrombauts/pickles-715/builds/19795186)

**Comment by darrencomeau** [comment]
Build now failing due to error

[build log](https://ci.appveyor.com/project/dirkrombauts/pickles-715/builds/19797848)
```
4347 ---------------------------------------------------------------------
4348   1) Fake.UnitTestCommon+FailedTestsException: NUnit test failed (2).
4349    at Fake.Testing.NUnit3.NUnit3(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\a\1\s\src\legacy\FakeLib\UnitTest\NUnit\NUnit3.fs:line 349
4350    at FSI_0005.Test.clo@28-4.Invoke(Unit _arg3) in C:\projects\pickles-715\test.fsx:line 29
4351    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\a\1\s\src\legacy\FakeLib\TargetHelper.fs:line 683
4352 ---------------------------------------------------------------------
```

**Comment by darrencomeau** [comment]
Fixed a few errors;
- [x] Not updating any of the build files
- [x] Incorrect namespace for unittest project
- [x] New version or specflow conflicts with other projects

Build now succeeds.
